services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server --console-address ":9001" /data/
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    hostname: minio
    volumes:
      - data:/data

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data:
